# External Brain 2 Starship preset
add_newline = false

format = """
$directory$git_branch$git_status$python$nodejs$env_var.EXTERNAL_PROFILE$time
$character """

[character]
success_symbol = "[â¯](bold green) "
error_symbol = "[âœ—](bold red) "

[directory]
truncation_length = 5
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = "î‚  "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
conflicted = "âš”ï¸ "
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡¡${ahead_count}â‡£${behind_count}"
modified = "âœš${count}"
staged = "â—${count}"
format = "([$all_status$ahead_behind]($style) )"

[python]
symbol = "ğŸ "
style = "yellow"
format = "via [$symbol$virtualenv($version )]($style)"

[nodejs]
symbol = "â¬¢ "
style = "bold green"
format = "via [$symbol($version )]($style)"

[env_var.EXTERNAL_PROFILE]
variable = "EXTERNAL_BRAIN_PROFILE"
style = "dimmed white"
format = "[$symbol($env_value) ]($style)"

[time]
disabled = false
style = "bold blue"
format = "[ğŸ•’ $time]($style) "
